<?php
if (!$this->isAuthorized) { // user is NOT authorized

    $urlData = array(
        'client_id'         => $this->CLIENT_ID,
        'response_type'     => 'code',
        'redirect_uri'      => 'http://oauth2.local'
                                . $this->url(array('controller' => 'facebook', 'action'=> 'callback')),
        'scope'             => 'user_about_me,user_photos,offline_access'
        // remember - in real world use state param to prevent CSRF!
    );
?>
<a href="https://www.facebook.com/dialog/oauth?<?=http_build_query($urlData);?>" title="Click to connect to Facebook">
    <img src="<?=$this->baseUrl();?>/images/connect-fb.png" alt="Connect to Facebook" />
</a>

<h3>This will move you to page:</h3>
<?php
Zend_Debug::dump('https://www.facebook.com/dialog/oauth?');
Zend_Debug::dump($urlData);
?>

<?php
} else { // user IS authorized
?>
<p>I'm authorized, let's get some data: </p>
<?php
if (!empty($this->me)) {
?>
<h3>User info</h3>
<ul>
    <li>Name: <?=$this->escape($this->me['name']);?>
    <li>Image: <img src="http://graph.facebook.com/<?=$this->escape($this->me['username']);?>/picture" />
    <li>Facebook profile: <a href="<?=$this->escape($this->me['link']);?>"><?=$this->escape($this->me['link']);?></a>
    <li>Bio: &bdquo;<?=$this->escape($this->me['bio']);?>&rdquo;
</ul>
<?php
}
if (!empty($this->photos['data'])) {
?>
<h3>Photos</h3>
<?php
    foreach($this->photos['data'] as $photo) {
        echo "<div style=\"width: 130px; height: 130px; float: left; margin: .5ex\">"
            . "<a href=\"{$photo['link']}\" target=_blank>"
            . "<img src=\"{$photo['picture']}\" alt=\""
            . (isset($photo['name']) ? $this->escape($photo['name']) : '')
            . "\" />"
            . "</a>"
            . "</div>\n";

    }
}
?>
<div style="clear: both"></div>
<?php
Zend_Debug::dump($this->me);
Zend_Debug::dump($this->photos);
}
?>
